import { callModel, clean, parseJsonContent, getGenerationProviderLabel, resolveLlmModel } from './proposalGenerator.js';

export const EXPLAIN_LEVELS = {
  kid: {
    label: '5th grader',
    audience: 'a curious 10-year-old in the 5th grade',
    rules:
      'Use very simple, everyday words and short sentences (about 12 words or fewer). Lean on a fun, concrete analogy. Avoid all jargon and acronyms. If a hard word is unavoidable, explain it right away in kid terms.'
  },
  highschool: {
    label: 'high schooler',
    audience: 'a curious high school student',
    rules:
      'Use plain language a teenager understands. You may use a few common technical words, but briefly explain any specialized ones. Keep sentences clear and not too long.'
  },
  undergrad: {
    label: 'undergraduate',
    audience: 'a first-year college student majoring in a different field',
    rules:
      'Use clear, direct language. Standard technical terms are fine, but briefly define specialized jargon the first time it appears.'
  },
  expert: {
    label: 'expert / peer',
    audience: 'a peer researcher working in a related field',
    rules:
      'Use precise, rigorous technical language and standard terminology. Be concise and assume domain familiarity. A glossary is usually unnecessary at this level.'
  }
};

const DEFAULT_LEVEL = 'kid';

function buildSystemPrompt(level) {
  const config = EXPLAIN_LEVELS[level] || EXPLAIN_LEVELS[DEFAULT_LEVEL];

  return `You are a skilled science communicator. Re-explain a research proposal so that ${config.audience} can understand it.

Reading-level rules:
${config.rules}

Return strict JSON with this exact shape:
{
  "tagline": "one short, catchy sentence that captures the big idea",
  "analogy": "an everyday analogy that makes the idea relatable",
  "whatItIs": "what the project is, in plain language",
  "whyItMatters": "why it matters and who it helps",
  "howItWorks": "how the approach works, explained simply",
  "glossary": [{ "term": "an unavoidable term", "plain": "its plain-language meaning" }],
  "layAbstract": "a 3-5 sentence plain-language abstract that could be pasted into the proposal as a lay summary"
}

Rules:
- Match the target reading level exactly in vocabulary and sentence length.
- Only use facts supported by the provided project content. Do not invent results or claims.
- Keep "glossary" to at most 5 entries. Use an empty array if no terms need defining.
- Return only the JSON object, with no extra commentary.`;
}

function buildSourceContent({ project, proposalLatex }) {
  const safeProject = project || {};

  return {
    title: clean(safeProject.title) || clean(safeProject.topic),
    problem: clean(safeProject.problem),
    method: clean(safeProject.method),
    evaluation: clean(safeProject.evaluation),
    timeline: clean(safeProject.timeline),
    resources: clean(safeProject.resources),
    proposalLatex: clean(proposalLatex).slice(0, 8000)
  };
}

export async function explainProposal({ project, proposalLatex, level, llmModel }) {
  const normalizedLevel = EXPLAIN_LEVELS[level] ? level : DEFAULT_LEVEL;
  const source = buildSourceContent({ project, proposalLatex });

  if (process.env.LLM_API_KEY && process.env.LLM_API_URL) {
    return explainWithApi({ source, level: normalizedLevel, llmModel });
  }

  return explainLocally({ source, level: normalizedLevel });
}

async function explainWithApi({ source, level, llmModel }) {
  const model = resolveLlmModel(llmModel);

  const systemPrompt = buildSystemPrompt(level);
  const payload = { level, source };
  const content = await callModel({ systemPrompt, payload, model, temperature: 0.3 });
  const parsed = parseJsonContent(content);

  return {
    mode: 'api',
    provider: getGenerationProviderLabel(model),
    level,
    levelLabel: EXPLAIN_LEVELS[level].label,
    ...coerceExplanation(parsed, source),
    transcript: {
      prompt: { systemPrompt, payload },
      rawResponse: content
    }
  };
}

function explainLocally({ source, level }) {
  return {
    mode: 'local-fallback',
    provider: 'template',
    level,
    levelLabel: EXPLAIN_LEVELS[level].label,
    ...buildLocalExplanation(source, level),
    transcript: {
      prompt: { level, source },
      rawResponse: 'Generated by local fallback because LLM_API_KEY or LLM_API_URL is not configured.'
    }
  };
}

function coerceExplanation(parsed, source) {
  const glossary = Array.isArray(parsed.glossary)
    ? parsed.glossary
      .map((entry) => ({ term: clean(entry.term), plain: clean(entry.plain) }))
      .filter((entry) => entry.term && entry.plain)
      .slice(0, 5)
    : [];

  const fallback = buildLocalExplanation(source, DEFAULT_LEVEL);

  return {
    tagline: clean(parsed.tagline) || fallback.tagline,
    analogy: clean(parsed.analogy) || fallback.analogy,
    whatItIs: clean(parsed.whatItIs) || fallback.whatItIs,
    whyItMatters: clean(parsed.whyItMatters) || fallback.whyItMatters,
    howItWorks: clean(parsed.howItWorks) || fallback.howItWorks,
    glossary,
    layAbstract: clean(parsed.layAbstract) || fallback.layAbstract
  };
}

function buildLocalExplanation(source, level) {
  const topic = source.title || 'this research project';
  const problem = source.problem || 'a problem that does not yet have a good solution';
  const method = source.method || 'a step-by-step approach that the researchers will build and test';
  const evaluation = source.evaluation || 'careful checks to see whether the idea actually works';

  return {
    tagline: `${topic}: turning a hard problem into something we can actually solve.`,
    analogy:
      'Think of it like building a helpful robot assistant: first you teach it the rules, then you let it practice, and then you check its homework to make sure it got things right.',
    whatItIs: `This project studies ${topic}. The main challenge is ${problem}.`,
    whyItMatters: `If it works, it could help people who deal with ${problem}, making the task faster, clearer, or fairer.`,
    howItWorks: `The plan is to use ${method}. Then the team measures success with ${evaluation}.`,
    glossary: [],
    layAbstract: `${topic} tackles ${problem}. The team plans to use ${method}, and then checks whether it works using ${evaluation}. The goal is a clear, useful result that ordinary people can understand and benefit from. (Generated by the local fallback explainer; reading level: ${level}.)`
  };
}
