import { DEFAULT_REQUIREMENTS, PROPOSAL_AUTHOR } from './mathlmDefaults.js';

/** Project fields aligned with the final submission proposal in deliverables/. */
export const SUBMISSION_PROJECT = {
  title:
    'Process-Based Reinforcement Learning with Step-Level Rewards for Mathematical Reasoning in Language Models',
  topic: 'Process-based reinforcement learning for mathematical reasoning in language models',
  problem:
    'Existing reinforcement learning (RL) methods for mathematical reasoning in large language models (LLMs) rely predominantly on sparse outcome-based rewards—binary signals indicating only whether a final answer is correct or incorrect. This approach provides no guidance on where or why a reasoning chain fails, yields low sample efficiency, and hinders generalization to harder multi-step problems. While recent work has explored process reward models (PRMs), there is no systematic framework combining dense step-level process rewards with scalable policy optimization (e.g., GRPO) and structured reasoning-path exploration (e.g., MCTS).',
  method:
    'We will use Group Relative Policy Optimization (GRPO) as the core policy update mechanism, leveraging its ability to stabilize training by comparing multiple sampled reasoning trajectories within each update group. Step-level rewards will be provided by a process reward model (PRM) trained on human-annotated and synthetic step-level correctness labels, augmented by an LLM-as-judge that evaluates the logical coherence and mathematical validity of each reasoning step. During inference, Monte Carlo Tree Search (MCTS) will explore candidate reasoning paths, using the PRM and LLM-as-judge scores as node evaluation signals to guide expansion and selection.',
  evaluation:
    'Research Questions and Hypotheses: RQ1: Does process-based reinforcement learning with dense step-level rewards improve multi-step mathematical reasoning accuracy relative to supervised fine-tuning and outcome-only RL baselines?\nMetrics and Benchmarks: Exact-match accuracy on GSM8K, MATH, AMC, and AIME; PRM agreement with human annotators on held-out problems; training stability via KL divergence.\nComparative Baselines: (1) supervised fine-tuning only; (2) outcome-only RL (PPO-style); (3) proposed GRPO with dense process rewards and MCTS-guided search.\nAblations and Sensitivity Analysis: Remove PRM component, disable MCTS, vary curriculum scheduling and self-consistency sample counts.\nAnalysis Plan: Report learning curves, error categories, and reproducibility artifacts including logged hyperparameters and evaluation scripts.\nSuccess Criteria: Demonstrate measurable improvement over credible baselines with stable training behavior and reproducible scripts sufficient for independent verification.',
  timeline:
    'Expected results: (1) A trained process reward model that predicts step-level correctness with >90% agreement with human annotators on held-out math problems. (2) An LLM policy that improves by 10--20% absolute accuracy on GSM8K and MATH benchmarks compared to outcome-only RL baselines. (3) Qualitative improvements in reasoning coherence, with fewer logical jumps and more verifiable intermediate steps. (4) Public release of a process-annotated dataset and evaluation harness.\nMilestone 1 (Months 1--2): Literature review and dataset curation. Assemble and annotate a process-level math reasoning dataset (e.g., from GSM8K, MATH, AoPS) with step-level labels; define annotation guidelines and quality controls.\nMilestone 2 (Months 2--4): Process reward model development. Train and evaluate PRM variants (classification, regression, and ranking heads); perform ablation on annotation sources and training regimes; select best PRM for downstream RL.\nMilestone 3 (Months 4--6): Search and planning integration. Implement tree-based reasoning search (beam/MCTS) using PRM and value head; benchmark search efficiency and solution quality against standard decoding.\nMilestone 4 (Months 6--9): Policy optimization and curriculum learning. Train LLM policies with PBRL using process + outcome rewards; implement curriculum from easy to hard problems; compare to outcome-only RL and supervised fine-tuning baselines.\nMilestone 5 (Months 9--11): Evaluation and analysis. Conduct comprehensive evaluation on in-distribution and out-of-distribution math benchmarks; perform error analysis and ablation studies; assess generalization to competition-level problems.\nMilestone 6 (Months 11--12): Dissemination and release. Prepare manuscript, release code, PRM weights, and process-annotated dataset; document risks, limitations, and future directions.',
  resources:
    'Budget for 2--3 part-time human annotators for 3--4 months to label approximately 10k reasoning trajectories with step-level correctness. GPU access for RL training (single A100 or equivalent cloud credits). PyTorch, Hugging Face Transformers, and experiment tracking (Weights & Biases or equivalent).',
  references:
    "Lightman, H., et al. (2023). 'Let's Verify Step by Step.' arXiv:2305.20050.\nWang, X., et al. (2023). 'Math-Shepherd: Verify and Reinforce LLMs Step-by-step without Human Annotations.' arXiv:2312.08935.\nOpenAI (2023). 'GPT-4 Technical Report.' arXiv:2303.08774.\nCobbe, K., et al. (2021). 'Training Verifiers to Solve Math Word Problems.' arXiv:2110.14168.\nWei, J., et al. (2022). 'Chain-of-Thought Prompting Elicits Reasoning in Large Language Models.' NeurIPS 2022.",
  layAbstract:
    'This project asks whether AI math reasoning can improve when models learn from step-by-step feedback—not only from whether the final answer is right—using GRPO training, process reward models, and search over reasoning paths.',
  requirements: DEFAULT_REQUIREMENTS
};

export { PROPOSAL_AUTHOR };
